# Generated by Django 4.1.4 on 2023-01-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(default='url', upload_to='pdf'),
            preserve_default=False,
        ),
    ]
